name: Build AIX Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Rush CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/shreyasms/rush-cli/main/scripts/install/install.sh | bash
          echo "$HOME/.rush/bin" >> $GITHUB_PATH

      - name: Build Extension
        run: rush build

      - name: Upload AIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Extension-AIX
          path: out/*.aix
