name: Build AIX Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build AIX Extension
        id: build
        uses: pavi2410/AIX-Action@main
        with:
          package-name: 'com.deeplink.app'

      - name: Upload AIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Extension-AIX
          path: ${{ steps.build.outputs.aix-path }}
